Homework2: Aliaksei Uhalnikau
belovmd/it-academy-python-spring pull request #31
Opened 2020-02-03 16:52 UTC by alexugalek

New branch with commits only of homework 2 tasks

2020-02-29 21:25 UTC, belovmd requested changes
Thank you for your work. It's great. 
Please address next paragraphs from review notes [Review Notes](https://github.com/belovmd/it-academy-python-spring/blob/master/homework_review/Homework2.md):
- 8
- 14
- 18

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_24.py
> +    return lambda x: x + num
lamdba is best solution here

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_26.py
> +    def _type(self):
it's unclear why do we need this property

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_26.py
> +        expr = temp_stack_str[0][1:-1]
indexing and slicing stack is not the best idea
stack should be used with pop and push (append) functions and that's all
also it's unclear why do we need str in list name :)

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_28.py
> +        return flag_1 == flag_2 == flag_3
and and and?

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_29.py
> +    return sorted(count_dict, key=lambda x: (-count_dict[x], x))[0]
pretty implicit line

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_30.py
> +    return time + ' p.m.' if time[:2] == '12' \
ternary operators shouldn't be used if they are multi-line

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_32.py
> +    sorted_items = sorted(dict_count,
`lst = dict_count.values(); lst.sort; return lst[::-1]?`

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_36.py
> +            if ch_pawn[1] == pawn[1] + 1 and \
pretty unclear implementation )) too many numbers and operations

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_4.py
> +    # return ' '.join([word for word in list_of_words if word])  Equal result
debug comments

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_45.py
> +        unit_army1_nmb = unit_army2_nmb = 0
this function looks too complex. it seems all this class can be implemented easier. 
you can not change it and use in further homework. (we'll have some for emulation with classes)

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_45.py
> +    def vampire_recovery(unit, attack):
all these methods should be put to according models

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_45.py
> +def fight(unit_1, unit_2, unit_1_2=None, unit_2_2=None):
we should move it to battle class,

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_52.py
> +def checkio(expression):
this task is often used during interview. please don't forget your stack solution.

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_55.py
> +            return f'[{self.font}]{self.text}[{self.font}]'
these f-strings ^)

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_8.py
> +    # Create a dict with keys consists from word chars
redundant comments

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_11.py
> +    """Instructions
missed full task description

2020-02-29 21:25 UTC, belovmd commented on src/Homework2New/task_15.py
> +    list_result = []
it seems this solution can be re-writed a bit more clear

2020-03-01 13:06 UTC, alexugalek commented on src/Homework2New/task_28.py
> +        return flag_1 == flag_2 == flag_3
My bad.

2020-03-01 13:08 UTC, alexugalek commented on src/Homework2New/task_30.py
> +    return time + ' p.m.' if time[:2] == '12' \
Got it

2020-05-03 10:30 UTC, belovmd reviewed
10

2020-05-03 10:30 UTC, closed without merging