Homework 3: Yuliya Golovach
belovmd/it-academy-python-spring pull request #40
Opened 2020-02-18 11:08 UTC by YuliyaGolovach

2020-03-29 16:26 UTC, belovmd requested changes
Thank you for your work. 
Please address next paragraphs from review notes [Review Notes](https://github.com/belovmd/it-academy-python-spring/blob/master/homework_review/Homework3.md):
- 2 
- 7
- 8
- 9

2020-04-05 20:16 UTC, YuliyaGolovach commented
I know that attentiveness in not my strength, but sometime i really get surprised how i could wrote this (this code), for example wrote smth. that solves a different task...

2020-05-03 16:27 UTC, belovmd reviewed
9

2020-05-03 16:27 UTC, belovmd commented on src/hw_3/t03_tuple_practice.py
> +tuple4 = tuple([[1, 2, 3], ], )
tuple([1,2,3],)

2020-05-03 16:27 UTC, closed without merging