Homework3
belovmd/it-academy-python-spring pull request #42
Opened 2020-02-19 19:12 UTC by JanGonza

2020-03-29 17:53 UTC, belovmd requested changes
Thank you for your work. 
Please address next paragraphs from review notes [Review Notes](https://github.com/belovmd/it-academy-python-spring/blob/master/homework_review/Homework3.md):
- 6
- 12
- 11
- 13

2020-03-29 17:53 UTC, belovmd commented on src/FizzBuzz.py
> +    if number % 3 == 0 == number % 5:
looks completely unclear

2020-03-29 17:53 UTC, belovmd commented on src/Сhocolate.py
> +Если k / 2 ** 7 <= 1 то можно получить k долек за t разломов.
why 7? missed solution description

2020-03-30 14:49 UTC, JanGonza commented on src/Сhocolate.py
> +Если k / 2 ** 7 <= 1 то можно получить k долек за t разломов.
Fixed
k / 2 ** t <= 1

2020-03-30 14:50 UTC, JanGonza commented on src/FizzBuzz.py
> +    if number % 3 == 0 == number % 5:
Fixed
if number % 15 == 0:

2020-05-03 16:32 UTC, belovmd reviewed
9,5

2020-05-03 16:32 UTC, closed without merging