Homework 2: Dmitry Radyukov
belovmd/it-academy-python-spring pull request #70
Opened 2020-03-27 12:17 UTC by DmitryRadyukov

add Homework2.py

2020-03-27 12:52 UTC, DmitryRadyukov commented
Add Homework 2, 3, 4

2020-04-05 16:24 UTC, belovmd requested changes
Thank you for your work. 
Please address next paragraphs from review notes [Review Notes](https://github.com/belovmd/it-academy-python-spring/blob/master/homework_review/Homework4.md):
- 25
- 26
- 27
- 28
- 29
- 30
- 13
- 20

2020-04-05 16:24 UTC, belovmd commented on Homework4.py
> +stud = [{input() for j in range(int(input()))} for i in range(int(input()))]
great

2020-05-03 19:08 UTC, belovmd reviewed
review issues not addressed. 
5

2020-05-03 19:08 UTC, closed without merging